#!/usr/bin/env bash
#
# Builds two generated files from network/config/addressing.conf and the node
# manifest:
#
#   network/config/static-nodes.json     the devp2p peer list
#   network/compose/compose.addressing.yml  fixed IPs for the compose stack
#
# Both come from one source file, so the IP a node is given and the IP its
# peers dial cannot disagree. The compose base file contains no addresses at
# all, which keeps it readable and keeps the generated part small.
#
# A full mesh rather than a bootnode: in a consortium every peer is known in
# advance, so discovery buys nothing and a bootnode would be a single point of
# failure for node joins.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="$REPO/network/genesis/manifest.json"
ADDRESSING="$REPO/network/config/addressing.conf"
NODES_OUT="$REPO/network/config/static-nodes.json"
COMPOSE_OUT="$REPO/network/compose/compose.addressing.yml"
P2P_PORT=30303

[[ -f "$MANIFEST" ]]   || { echo "no manifest. run ./tools/gen-network.sh first"; exit 1; }
[[ -f "$ADDRESSING" ]] || { echo "missing $ADDRESSING"; exit 1; }

SUBNET="$(grep -E '^SUBNET=' "$ADDRESSING" | cut -d= -f2)"
[[ -n "$SUBNET" ]] || { echo "no SUBNET= line in $ADDRESSING"; exit 1; }

trim() {
  local s="$1"
  s="${s#"${s%%[![:space:]]*}"}"
  printf '%s' "${s%"${s##*[![:space:]]}"}"
}

SERVICES=(); NODES=(); IPS=()
while IFS='|' read -r service node ip || [[ -n "$service" ]]; do
  service="$(trim "${service:-}")"
  [[ -z "$service" || "${service:0:1}" == "#" || "$service" == SUBNET=* ]] && continue
  NODES+=("$(trim "${node:-}")")
  IPS+=("$(trim "${ip:-}")")
  SERVICES+=("$service")
done < "$ADDRESSING"

echo "==> static nodes"
{
  echo "["
  for i in "${!NODES[@]}"; do
    node="${NODES[$i]}"
    pub="$(jq -r --arg n "$node" '.nodes[] | select(.node==$n) | .pubkey' "$MANIFEST")"
    if [[ -z "$pub" || "$pub" == "null" ]]; then
      echo "node $node is in addressing.conf but not in the manifest" >&2
      exit 1
    fi
    sep=","; [[ "$i" -eq $(( ${#NODES[@]} - 1 )) ]] && sep=""
    printf '  "enode://%s@%s:%s"%s\n' "${pub#0x}" "${IPS[$i]}" "$P2P_PORT" "$sep"
  done
  echo "]"
} > "$NODES_OUT"
jq -e . "$NODES_OUT" >/dev/null
jq -r '.[]' "$NODES_OUT" | sed 's/^/    /'

echo "==> compose addressing override"
{
  echo "# Generated by tools/gen-static-nodes.sh. Do not edit."
  echo "# Source of truth: network/config/addressing.conf"
  echo ""
  echo "networks:"
  echo "  consortium:"
  echo "    name: loc-consortium"
  echo "    ipam:"
  echo "      config:"
  echo "        - subnet: $SUBNET"
  echo ""
  echo "services:"
  for i in "${!SERVICES[@]}"; do
    echo "  ${SERVICES[$i]}:"
    echo "    networks:"
    echo "      consortium:"
    echo "        ipv4_address: ${IPS[$i]}"
    echo "        aliases: [${NODES[$i]}.loc.consortium]"
  done
} > "$COMPOSE_OUT"

echo "    wrote $COMPOSE_OUT"
